// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkoutLog.API.Data;

#nullable disable

namespace WorkoutLog.API.Data.Migrations
{
    [DbContext(typeof(WorkoutLogDBContext))]
    partial class WorkoutLogDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("ExerciseMuscleGroup", b =>
                {
                    b.Property<int>("ExercisesExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OtherMusclesWorkedMuscleGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExercisesExerciseId", "OtherMusclesWorkedMuscleGroupId");

                    b.HasIndex("OtherMusclesWorkedMuscleGroupId");

                    b.ToTable("ExerciseMuscleGroup");
                });

            modelBuilder.Entity("WorkoutLog.API.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquipmentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EquipmentId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("WorkoutLog.API.Models.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PrimaryMusclesWorkedId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExerciseId");

                    b.HasIndex("EquipmentId")
                        .IsUnique();

                    b.HasIndex("ExerciseTypeId")
                        .IsUnique();

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("WorkoutLog.API.Models.ExerciseType", b =>
                {
                    b.Property<int>("ExerciseTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ExerciseTypeId");

                    b.ToTable("ExerciseTypes");
                });

            modelBuilder.Entity("WorkoutLog.API.Models.Goal", b =>
                {
                    b.Property<int>("GoalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GoalType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GoalValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GoalId");

                    b.HasIndex("ExerciseId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("WorkoutLog.API.Models.Muscle", b =>
                {
                    b.Property<int>("MuscleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MuscleGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MuscleId");

                    b.HasIndex("MuscleGroupId");

                    b.ToTable("Muscles");
                });

            modelBuilder.Entity("WorkoutLog.API.Models.MuscleGroup", b =>
                {
                    b.Property<int>("MuscleGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MuscleGroupId");

                    b.ToTable("MuscleGroups");
                });

            modelBuilder.Entity("WorkoutLog.API.Models.OptimalVolume", b =>
                {
                    b.Property<int>("OptimalVolumeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MuscleGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("OptimalVolumeId");

                    b.HasIndex("MuscleGroupId")
                        .IsUnique();

                    b.ToTable("OptimalVolumes");
                });

            modelBuilder.Entity("WorkoutLog.API.Models.Preference", b =>
                {
                    b.Property<int>("PreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyMeasurementUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultTimerDuration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DistanceUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LogRPE")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximumTimerDuration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowExerciseInformation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowExerciseSummary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WeightUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PreferenceId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Preferences");
                });

            modelBuilder.Entity("WorkoutLog.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bodyweight")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainingStyles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WorkoutLog.API.Models.UserWorkout", b =>
                {
                    b.Property<int>("UserWorkoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserWorkoutId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("WorkoutId");

                    b.ToTable("UserWorkouts");
                });

            modelBuilder.Entity("WorkoutLog.API.Models.Workout", b =>
                {
                    b.Property<int>("WorkoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateNextScheduled")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavourited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalVolume")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkoutId");

                    b.HasIndex("UserId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("WorkoutLog.API.Models.WorkoutExercise", b =>
                {
                    b.Property<int>("WorkoutExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkoutExerciseId");

                    b.HasIndex("ExerciseId")
                        .IsUnique();

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutExercises");
                });

            modelBuilder.Entity("WorkoutLog.API.Models.WorkoutExerciseSet", b =>
                {
                    b.Property<int>("WorkoutExerciseSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RateOfPerceivedExertionRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RepsInReserveRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkoutExerciseSetType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WorkoutExerciseSetId");

                    b.HasIndex("WorkoutExerciseId");

                    b.ToTable("WorkoutExerciseSets");
                });

            modelBuilder.Entity("WorkoutLog.API.Models.WorkoutRecord", b =>
                {
                    b.Property<int>("WorkoutRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkoutExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkoutRecordId");

                    b.HasIndex("WorkoutExerciseId")
                        .IsUnique();

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutRecords");
                });

            modelBuilder.Entity("ExerciseMuscleGroup", b =>
                {
                    b.HasOne("WorkoutLog.API.Models.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutLog.API.Models.MuscleGroup", null)
                        .WithMany()
                        .HasForeignKey("OtherMusclesWorkedMuscleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkoutLog.API.Models.Exercise", b =>
                {
                    b.HasOne("WorkoutLog.API.Models.Equipment", "Equipment")
                        .WithOne("Exercise")
                        .HasForeignKey("WorkoutLog.API.Models.Exercise", "EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutLog.API.Models.MuscleGroup", "PrimaryMusclesWorked")
                        .WithOne("Exercise")
                        .HasForeignKey("WorkoutLog.API.Models.Exercise", "ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutLog.API.Models.ExerciseType", "ExerciseType")
                        .WithOne("Exercise")
                        .HasForeignKey("WorkoutLog.API.Models.Exercise", "ExerciseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("ExerciseType");

                    b.Navigation("PrimaryMusclesWorked");
                });

            modelBuilder.Entity("WorkoutLog.API.Models.Goal", b =>
                {
                    b.HasOne("WorkoutLog.API.Models.Exercise", "Exercise")
                        .WithOne("Goal")
                        .HasForeignKey("WorkoutLog.API.Models.Goal", "ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutLog.API.Models.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkoutLog.API.Models.Muscle", b =>
                {
                    b.HasOne("WorkoutLog.API.Models.MuscleGroup", "MuscleGroup")
                        .WithMany("Muscles")
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("WorkoutLog.API.Models.OptimalVolume", b =>
                {
                    b.HasOne("WorkoutLog.API.Models.MuscleGroup", "MuscleGroup")
                        .WithOne("OptimalVolume")
                        .HasForeignKey("WorkoutLog.API.Models.OptimalVolume", "MuscleGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("WorkoutLog.API.Models.Preference", b =>
                {
                    b.HasOne("WorkoutLog.API.Models.User", "User")
                        .WithOne("Preference")
                        .HasForeignKey("WorkoutLog.API.Models.Preference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkoutLog.API.Models.UserWorkout", b =>
                {
                    b.HasOne("WorkoutLog.API.Models.User", "User")
                        .WithOne("UserWorkoutId")
                        .HasForeignKey("WorkoutLog.API.Models.UserWorkout", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutLog.API.Models.Workout", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("WorkoutLog.API.Models.Workout", b =>
                {
                    b.HasOne("WorkoutLog.API.Models.User", "User")
                        .WithMany("Workouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkoutLog.API.Models.WorkoutExercise", b =>
                {
                    b.HasOne("WorkoutLog.API.Models.Exercise", "Exercise")
                        .WithOne("WorkoutExercise")
                        .HasForeignKey("WorkoutLog.API.Models.WorkoutExercise", "ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutLog.API.Models.Workout", "Workout")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("WorkoutLog.API.Models.WorkoutExerciseSet", b =>
                {
                    b.HasOne("WorkoutLog.API.Models.WorkoutExercise", "WorkoutExercise")
                        .WithMany("WorkoutExerciseSets")
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutExercise");
                });

            modelBuilder.Entity("WorkoutLog.API.Models.WorkoutRecord", b =>
                {
                    b.HasOne("WorkoutLog.API.Models.WorkoutExercise", "WorkoutExercise")
                        .WithOne("WorkoutRecord")
                        .HasForeignKey("WorkoutLog.API.Models.WorkoutRecord", "WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutLog.API.Models.Workout", "Workout")
                        .WithMany("WorkoutRecords")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");

                    b.Navigation("WorkoutExercise");
                });

            modelBuilder.Entity("WorkoutLog.API.Models.Equipment", b =>
                {
                    b.Navigation("Exercise")
                        .IsRequired();
                });

            modelBuilder.Entity("WorkoutLog.API.Models.Exercise", b =>
                {
                    b.Navigation("Goal")
                        .IsRequired();

                    b.Navigation("WorkoutExercise")
                        .IsRequired();
                });

            modelBuilder.Entity("WorkoutLog.API.Models.ExerciseType", b =>
                {
                    b.Navigation("Exercise")
                        .IsRequired();
                });

            modelBuilder.Entity("WorkoutLog.API.Models.MuscleGroup", b =>
                {
                    b.Navigation("Exercise")
                        .IsRequired();

                    b.Navigation("Muscles");

                    b.Navigation("OptimalVolume")
                        .IsRequired();
                });

            modelBuilder.Entity("WorkoutLog.API.Models.User", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("Preference")
                        .IsRequired();

                    b.Navigation("UserWorkoutId")
                        .IsRequired();

                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("WorkoutLog.API.Models.Workout", b =>
                {
                    b.Navigation("WorkoutExercises");

                    b.Navigation("WorkoutRecords");
                });

            modelBuilder.Entity("WorkoutLog.API.Models.WorkoutExercise", b =>
                {
                    b.Navigation("WorkoutExerciseSets");

                    b.Navigation("WorkoutRecord")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
